# Generated by Django 5.0.7 on 2024-08-16 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_alter_article_options_scope_topic_scope_topic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={},
        ),
    ]
