# Generated by Django 5.0.7 on 2024-08-19 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measurement',
            name='image',
        ),
        migrations.AlterField(
            model_name='measurement',
            name='created_at',
            field=models.DateField(auto_now=True, verbose_name='Дата и время измерения'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='temperature',
            field=models.FloatField(verbose_name='Температура измерения'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='description',
            field=models.CharField(max_length=100, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Название'),
        ),
    ]
